collections:
    devopsma:
      output: true 
    blog:
      output: true
    awards:
      output: true
    integrations:
      output: true
    


 
defaults:
  

  - 
    scope: 
      path: ""
      type: devopsma
    values: 
      issuedBy: Anju M Dominic
      issuedInstitute: QUADRALOGICS
      dateOfIssue: 19 October 2020
      program: DevOps Master Architect
      advCTAName: Enrol Now
      advCTALink: https://quadralogics.com/training/DevOpsMasterArchitect.html
      CTAText: Learn hands-on DevOps with QUADRALOGICS
      advBGImagelink: https://certifyme.online/img/certificate/devopsma/DMW1.png
      brandLogo: https://certifyme.online/img/certificate/devopsma/logo.png
      brandMessage: QUADRALOGICS ,India's premier DevXOps Training & Consulting Firm. We enable you with the technical know how to adopt DevOps in it's true essence that too in a hands-on way. 
      contactPh_number: +91-6362315334
      contactEmail: info@quadralogics.com
      contactCompanyWebSiteLink: www.quadralogics.com
      text: This certificate is issued to recognise the participant for successfully completing all the requirements for the DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months. 
      certificatePath: https://certifyme.online/img/certificate/devopsma/Badges/DMA.jpg
  - 
    scope: 
      path: "_devopsma/Ansible"
      type: devopsma
    values: 
      program: Ansible module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Ansible Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.    
  - 
    scope: 
      path: "_devopsma/Puppet"
      type: devopsma
    values: 
      program: Puppet module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Puppet Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.
  - 
    scope: 
      path: "_devopsma/InSpec"
      type: devopsma
    values: 
      program: InSpec module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the InSpec Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.
  - 
    scope: 
      path: "_devopsma/Nagios"
      type: devopsma
    values: 
      program: Nagios module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Nagios Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.
  - 
    scope: 
      path: "_devopsma/Kubernetes"
      type: devopsma
    values: 
      program: Kubernetes module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Kubernetes Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.
  - 
    scope: 
      path: "_devopsma/CloudFormation"
      type: devopsma
    values: 
      program: CloudFormation module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the CloudFormation Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.
  - 
    scope: 
      path: "_devopsma/Terraform"
      type: devopsma
    values: 
      program: Terraform module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Terraform Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.
  - 
    scope: 
      path: "_devopsma/Chef"
      type: devopsma
    values: 
      program: Chef module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Chef Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.    
  - 
    scope: 
      path: "_devopsma/Docker"
      type: devopsma
    values: 
      program: Docker module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Docker Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.
  
  - 
    scope: 
      path: "_devopsma/Jenkins"
      type: devopsma
    values: 
      program: Jenkins module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Jenkins Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.

  - 
    scope: 
      path: "_devopsma/Git"
      type: devopsma
    values: 
      program: Git module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Git Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.    
  
  - 
    scope: 
      path: "_devopsma/CloudFormation"
      type: devopsma
    values: 
      program: CloudFormation module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the CloudFormation Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.

  
      
      
      # Site settings
title: Certify Me  
email: info@quadralogics.com
description: CertifyMe.Online is an end-to-end solution for creating, issuing, and managing your Digital Credentials
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
company: QuadraLogics
#Heading 
Head1: Certify Me.Online 
Head2: Your end-to-end solution for creating, issuing, and managing Digital Credentials
Head3: We add more value to your Training & Certifications 
HeadCTA: Request a Demo
HeadCTALink: mailto:info@quadralogics.com?subject = Express Interest&body = I  would like to know more about how certifyme.online could add value to my  Training & Certifications.
#Call to action
USPH: ABOUT
USP: CertifyMe.Online is "Your Trusted Digital Credential Publishing Platform". We believe in your programs and their impact on the audience. We are here to help you extend your gratitude and appreciation to all the attendees for their love and support. The digital credentials will be a warm welcome for all the attendees to make them feel like a part of your amazing program. These easily sharable credentials will increase the visibility of your program on different social media platforms and help create an organic impression for the event and help the event reach a larger spectrum of audience.
 Do you also want a little bit of pre-and post-engagement of your event? Then we understand you and are always available to support you because "Your Event Matters!"

TContentH: Download Training Contents
TContentB: Topics include Docker, Kubernetes, Jenkins, Puppet, Ansible, Chef, Terraform, AWS Cloud formation, Nagios, Git, & InSpec
TContentLink: https://drive.google.com/u/0/uc?id=1jIOXTEolfSOy2nYpC1QxoVlfX_xn5Fns&export=download

#services
ServicesHeading:  How does it work?

Services1H: Step 1.  Sign Up  

Services1: Sign up, create your Credentials templates, and upload awardee names. We understand your data privacy concerns hence you need not upload any sensitive data like awardees Email ID.



Services2H: Step 2.  Generate Credentials 
Services2: CertifyMe.Online will help you generate the Credential Webpages for each awardee. Each Credential is stored in a unique web address with a QR Code embedded on it for verifiability. 

Services3H: Step 3. Issue Credentials 
Services3: Sit back & relax as our application automates the mundane task of Credential authoring & publication. The generated Credential Webpages are mobile/social media-friendly and sharable.

#features 

FeatureHeading:  Adding more value

Feature1H:   Digitized Certificates & Badges
Feature1: Gain more attraction to your conferences & events by publishing Digitized Credential Webpages to your speakers/delegates. These digital Credential of recognition acts as a digital souvenirs.

Feature2H: Gain More Visibility
Feature2: These sharable Credentials enable you drive 10X more relevant traffic to your events over paid advertisements. It also generates a lot of social media engagements, boosting your event's visibility.

Feature3H:  Un-lock advertising space 
Feature3: Our Credential Webpages are customizable to include a branding banner and CTA button. Utilize this space to market your products/services or resell it to your lead sponsors.

Feature4H: Verifiable CREDENTIALS   
Feature4: Each of our Credentials is enabled with a QR Code to establish authenticity seamlessly. This also ensures our Credentials can't be forged. We also have email-based verification.
#Clinets
clinetsH : Sample Cetificate WebPage

#Portfolio


#Ribbon 
RHead1: Get Certified Now
RHead2: 
RHead3: 
RCTA:  Enroll !

ph_number: +91-6362315334
github_username: linkedin/company/quadralogics

footer: Â©  2020  www.quadralogics.com , certifyme.online is a QuadraLogics concern 



# Build settings
markdown: kramdown


